### ISSUE TITLE
encoded_span missing.

### ISSUE THREAD

**Issue by yzexeter** [qiajigou/flask-zipkin#16]
Hi. I follow the instruction here but I have an error. 
TypeError: default_handler() missing 1 required positional argument: 'encoded_span'

I think this is because I may lose the span for the entry service. But I actually added it. 
My code is as below:
![image](https://user-images.githubusercontent.com/18598611/28834585-86d4db16-76da-11e7-8674-3ed91bcccb3b.png)

@zipkin.transport_handler
def default_handler(self, encoded_span):
    body = str.encode('\x0c\x00\x00\x00\x01') + encoded_span
    return requests.post(
                'http://144.173.55.61:9411/api/v1/spans',
        data=body,
        headers={'Content-Type': 'application/x-thrift'},)

#index
#@zipkin_span(service_name='my_service', span_name='index',transport_handler=default_handler, sample_rate=100)
@app.route('/')
def index():
        with zipkin_span(
                service_name='webapp',
                span_name='index',
                transport_handler=default_handler,
                port=9411,
                sample_rate=100, #0.05, # Value between 0.0 and 100.0
                ):
                return render_template('home.html')

Could you please help me with it?

**Comment by killpanda** [comment]
could you try to use `def default_handler(encoded_span):` instead of  `def default_handler(self, encoded_span):` ?

**Comment by yzexeter** [comment]
Thank you. I already have solved it. The same as you suggest.
