### ISSUE TITLE
zipkin post span with http code 400 

### ISSUE THREAD

**Issue by chestarss** [qiajigou/flask-zipkin#17]
zipkin-server log:
Cannot decode spans due to IllegalArgumentException(Error reading List<Span> from TBinary)

when i modify like this ,it works. 
 39
 40     def default_handler(self, encoded_span):
 41         try:
 42             #body = str.encode('\x0c\x00\x00\x00\x01') + encoded_span
 43             body = encoded_span

**Comment by adriancole** [comment]
Maybe related to recent py_zipkin update?

**Comment by danfairs** [comment]
Just to confirm I encountered this issue, and using the suggested fix worked for me (posting to Google's Stackdriver zipkin collector, for what it's worth).

**Comment by faalin** [comment]
I have same problem

**Comment by faalin** [comment]
I have the same problem

**Comment by adriancole** [comment]
@qiajigou do you have some time to sort this out or do you need help?

**Comment by killpanda** [comment]
@adriancole fixed in PR above. thanks  @faalin  👍
