### ISSUE TITLE
400 Bad request from handler transport

### ISSUE THREAD

**Issue by ndh96coder** [qiajigou/flask-zipkin#25]
Here is my code server: 
[https://onlinegdb.com/r1gZ6lnFH](https://onlinegdb.com/r1gZ6lnFH)

After curl localhost:8080 the console show:
call zipkin transport_handler
code = 400, text = Expected value at line 1 column 1 path $ reading List<Span> from json , reason = Bad Request

How can i Fixed it. Thanks you

**Comment by killpanda** [comment]
For current version, please use v1 version API instead of v2 one.

Change DSN from

```
ZIPKIN_BASE_URL = "http://localhost:9411/api/v2/spans"
```

To 

```
ZIPKIN_BASE_URL = "http://localhost:9411/api/v1/spans"
```
