### ISSUE TITLE
Does flask-zipkin support Zipkin v2?

### ISSUE THREAD

**Issue by meteormatt** [qiajigou/flask-zipkin#26]
I test with flask-zipkin, but find it only support Zipkin v1 version **/api/v1/spans**. Failed on Zipkin v2 version **/api/v2/spans**.

**Comment by adriancole** [comment]
https://github.com/Yelp/py_zipkin supports it so I suppose it a a matter of
integrating here

**Comment by meteormatt** [comment]
> https://github.com/Yelp/py_zipkin supports it so I suppose it a a matter of integrating here

OK. I will look at it. Thanks. 😄
