### ISSUE TITLE
add test 

### ISSUE THREAD

**Issue by killpanda** [qiajigou/flask-zipkin#6]

**Comment by GuoJing** [comment]
and new release and readme and wiki and ...

**Comment by killpanda** [comment]
and test!

**Comment by GuoJing** [comment]
<img width="300" alt="cat" src="https://user-images.githubusercontent.com/363073/28454334-7c485e30-6e2d-11e7-89cb-bd2271d1061d.png">

**Comment by killpanda** [comment]
https://github.com/qiajigou/flask-zipkin/pull/14
